name: Build Documentation

on: 
  push:
    paths-ignore:
    - 'README.md'
    - 'CHANGELOG.md'

jobs:
  Docs:
    defaults:
      run:
        shell: pwsh
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Update Pip
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        
    - name: Install phishbench
      run: |
        pip install -r requirements.txt
        pip install .

    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
        
    - uses: actions/upload-artifact@v2
      with:
        name: DocumentationHTML
        path: docs/_build/html/
