name: Email Integration Test

on: 
  push:
    paths-ignore:
    - 'README.md'
    - 'CHANGELOG.md'
    - 'docs/**'

defaults:
    run: 
        shell: pwsh

jobs:
  Integration-Tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # os: [windows-latest, ubuntu-latest]
        os: [Windows, Linux]
      fail-fast: false

    steps:
    - name: Install whois
      run: sudo apt-get install whois
      if: runner.os == 'Linux'

    - name: Test whois
      run: |
        whois google.com
      if: runner.os == 'Linux'
    
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
      if: runner.os == 'windows-latest'
    
    - name: Update Pip
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        
    - name: Install phishbench
      run: |
        pip install -r requirements.txt
        pip install .

    - name: Email 1-Step test
      run: phishbench -f Test.ini -c
      working-directory: tests/integration tests/email_one_step

    - name: Email 2-Step test
      run: |
        phishbench -f Test_A.ini -c
        phishbench -f Test_B.ini -c
      working-directory: tests/integration tests/email_two_step
    
    - name: Upload Logs
      uses: actions/upload-artifact@v2
      with:
        name: Email Integration Test ${{github.run_id}} - ${{runner.os}} Results
        path: tests/integration tests/*/PhishBench Output/phishbench.log
        if-no-files-found: error
