name: Unit Test

on: 
  push:
    paths-ignore:
    - 'README.md'
    - 'CHANGELOG.md'
    - 'docs/**'

defaults:
    run: 
        shell: pwsh

jobs:
  Unit-Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        # os: [Windows, Linux]
      fail-fast: false

    steps:

      # - name: Install whois
      #   run: |
      #     sudo apt-get install whois
      #   if: runner.os == 'Linux'

      - name: Set up Python 3.7
        uses: actions/setup-python@v3
        with:
          python-version: 3.7

      - uses: actions/checkout@v2
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # - name: Install Test Dependencies
      #   run: pip install -r tests/requirements.txt

      - name: Test with Nose
        run: nose2 --with-coverage
        