name: Unit Test

on: push

defaults:
    run: 
        shell: pwsh

jobs:
  Unit-Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [windows-latest, ubuntu-latest]
        os: [Windows, Linux]
      fail-fast: false
    steps:
    - name: Install whois
      run: |
        sudo apt-get install whois
      if: runner.os == 'Linux'
    - name: Test whois
      run: |
        whois google.com
      if: runner.os == 'Linux'

    - uses: actions/checkout@v2

    # - name: Set up Python 3.7
    #   uses: actions/setup-python@v1
    #   with:
    #     python-version: 3.7
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Nose
      run: pip install --ignore-installed nose coverage

    - name: Test with Nose
      run: nosetests --with-coverage --cover-package phishbench
    

        